[project]
name = "expenseshistory"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
readme = "README.md"
dependencies = [
    "pyinstaller>=6.22.2",
    "pyqt6>=6.11.0",
    "pyqtgraph>=0.14.0",
    "sqlalchemy>=2.0.52",
]

[dependency-groups]
dev = []

[tool.uv]
package = false
default-groups = "all"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
